CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    is_active_user BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock (
    ref VARCHAR(50) PRIMARY KEY,
    qty INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS movement (
    id SERIAL PRIMARY KEY,
    ref VARCHAR(50) NOT NULL,
    qty INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_id INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS production (
    id SERIAL PRIMARY KEY,
    ref VARCHAR(50) NOT NULL,
    qty INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_id INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    action VARCHAR(120) NOT NULL,
    details TEXT NOT NULL,
    actor_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
